version: '3.9'

services:

  web:
    container_name: rentapp-backend
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true