# Generated by Django 4.0.3 on 2022-04-04 14:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_propertyitem_address_alter_propertyitem_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='propertyitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
