# Generated by Django 4.0.3 on 2022-06-13 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_user_gapi_user_type_set'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gapi_user_type_set',
        ),
    ]
