# Generated by Django 4.0.3 on 2022-07-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_user_gapi_user_type_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyitem',
            name='address',
            field=models.TextField(default='', max_length=256),
        ),
    ]
