# Generated by Django 4.0.3 on 2022-07-17 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_propertyitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyitem',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
