# Generated by Django 4.0.3 on 2022-07-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_propertyitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyitem',
            name='address',
            field=models.TextField(max_length=256),
        ),
    ]
