# Generated by Django 4.0.3 on 2022-07-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_propertyitem_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyitem',
            name='city',
            field=models.TextField(max_length=50),
        ),
    ]
