# Generated by Django 4.0.3 on 2022-07-21 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_propertyitem_rent_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyitem',
            old_name='rent_due_date',
            new_name='rent_due_day',
        ),
    ]
