# Generated by Django 4.0.3 on 2022-07-22 13:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_rename_rent_due_date_propertyitem_rent_due_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyitem',
            name='currency',
            field=models.PositiveSmallIntegerField(choices=[(1, 'EUR'), (2, 'LEI')], default=2),
        ),
        migrations.AlterField(
            model_name='propertyitem',
            name='rent_due_day',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
    ]
