# Generated by Django 4.0.3 on 2022-07-25 14:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_propertyitem_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyitem',
            name='rent_due_day',
            field=models.PositiveIntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)]),
        ),
    ]
