# Generated by Django 4.0.3 on 2022-08-11 13:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField(max_length=256)),
                ('closed', models.BooleanField(default=False)),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.propertyitem')),
            ],
        ),
        migrations.CreateModel(
            name='OwnerSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('properties_listed', models.PositiveSmallIntegerField(default=0)),
                ('income', models.PositiveIntegerField(default=0)),
                ('expenses', models.PositiveIntegerField(default=0)),
                ('open_issues', models.PositiveSmallIntegerField(default=0)),
                ('overdue', models.PositiveSmallIntegerField(default=0)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RentInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_id', models.PositiveSmallIntegerField()),
                ('owner_id', models.PositiveSmallIntegerField()),
                ('tenant_id', models.PositiveSmallIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('due_day', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
