# Generated by Django 4.0.3 on 2022-08-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_issue_ownersummary_rentinvoice_delete_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentinvoice',
            name='currency',
            field=models.CharField(default='LEI', max_length=5),
        ),
    ]
