# Generated by Django 4.0.3 on 2022-08-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_rentinvoice_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentinvoice',
            name='currency',
            field=models.CharField(default='LEI', max_length=4),
        ),
    ]
