# Generated by Django 4.0.3 on 2022-08-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rentinvoice_user_auth_provider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentinvoice',
            name='created_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
