# Generated by Django 4.0.3 on 2022-08-12 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_rentinvoice_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentinvoice',
            name='created_at',
        ),
    ]
