# Generated by Django 4.0.3 on 2022-08-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_rentinvoice_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentinvoice',
            name='created_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
