# Generated by Django 4.0.3 on 2022-08-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_rentinvoice_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentinvoice',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
