# Generated by Django 4.0.3 on 2022-08-31 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_rentinvoice_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyitem',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
