# Generated by Django 4.0.3 on 2022-09-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_rename_property_owner_id_issue_property_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='cost',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
