# Generated by Django 4.0.3 on 2022-09-15 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_issue_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='property_name',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
