# Generated by Django 4.0.3 on 2022-09-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_issue_property_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='property_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
