# Generated by Django 4.0.3 on 2022-09-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_issue_property_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentinvoice',
            name='property_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
