# Generated by Django 4.0.3 on 2022-10-28 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_propertyitem_tenant_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('message', models.TextField(max_length=256)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('linked_to_issue', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.issue')),
            ],
        ),
    ]
