# Generated by Django 4.0.3 on 2022-10-28 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_issuemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='created_by',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='issue_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
