# Generated by Django 4.0.3 on 2022-10-28 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_issue_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuemessage',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issuemessage',
            name='linked_to_issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.issue'),
        ),
    ]
