# Generated by Django 4.0.3 on 2022-10-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_issuemessage_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuemessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
