# Generated by Django 4.0.3 on 2022-10-31 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_alter_issuemessage_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='linked_to_property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.propertyitem'),
        ),
    ]
