# Generated by Django 4.0.3 on 2022-10-31 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_alter_issue_linked_to_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuemessage',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issuemessage',
            name='linked_to_issue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.issue'),
        ),
    ]
