# Generated by Django 4.0.3 on 2022-11-10 17:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_alter_issue_linked_to_property_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuemessage',
            name='user_type',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)]),
        ),
    ]
