# Generated by Django 4.0.3 on 2022-11-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0033_issuemessage_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentinvoice',
            name='tenant_email',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
