# Generated by Django 4.0.3 on 2022-12-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_rentinvoice_tenant_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyitem',
            name='coords',
            field=models.JSONField(null=True),
        ),
    ]
