# Generated by Django 4.0.3 on 2022-12-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0035_propertyitem_coords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyitem',
            name='coords',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
