# Generated by Django 4.0.3 on 2022-12-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_alter_propertyitem_coords'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyitem',
            name='rental_first_day',
            field=models.DateField(null=True),
        ),
    ]
